USE shakeeat;

ALTER TABLE food_item COMMENT = '菜单库主表, 保存可参与推荐的食物';
ALTER TABLE food_item
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键 ID',
    MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '食物名称, 如黄焖鸡米饭',
    MODIFY COLUMN emoji VARCHAR(20) DEFAULT NULL COMMENT '展示用 emoji',
    MODIFY COLUMN steps TEXT DEFAULT NULL COMMENT '基础步骤说明, 用于结果页展示',
    MODIFY COLUMN image_url VARCHAR(255) DEFAULT NULL COMMENT '食物图片地址',
    MODIFY COLUMN order_url VARCHAR(500) DEFAULT NULL COMMENT '外卖或购买链接, 用于结果页直达下单',
    MODIFY COLUMN weight INT NOT NULL DEFAULT 100 COMMENT '基础权重, 越大越容易被摇中',
    MODIFY COLUMN reference_price DECIMAL(10, 2) DEFAULT NULL COMMENT '参考价格, V1 只做轻度预算修正',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用, 1 启用, 0 停用',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记, 0 未删除, 1 已删除',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE food_tag COMMENT = '标签字典表, 用于模式筛选和偏好设置';
ALTER TABLE food_tag
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键 ID',
    MODIFY COLUMN name VARCHAR(50) NOT NULL COMMENT '标签名称, 如外卖, 辣, 轻食',
    MODIFY COLUMN icon VARCHAR(50) DEFAULT NULL COMMENT '标签图标或 emoji',
    MODIFY COLUMN tag_type VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' COMMENT '标签类型, SYSTEM 系统标签, CUSTOM 自定义标签',
    MODIFY COLUMN sort INT NOT NULL DEFAULT 0 COMMENT '排序值, 越小越靠前',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用, 1 启用, 0 停用',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记, 0 未删除, 1 已删除',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE food_item_tag_rel COMMENT = '食物与标签关系表, 一个食物可关联多个标签';
ALTER TABLE food_item_tag_rel
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键 ID',
    MODIFY COLUMN food_id BIGINT NOT NULL COMMENT '食物 ID',
    MODIFY COLUMN tag_id BIGINT NOT NULL COMMENT '标签 ID';

ALTER TABLE user_preference COMMENT = '用户偏好表, 当前单用户只有一条记录';
ALTER TABLE user_preference
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID, 当前 V1 固定为 1',
    MODIFY COLUMN favorite_tag_ids JSON DEFAULT NULL COMMENT '喜欢标签 ID 数组, 用于提高命中权重',
    MODIFY COLUMN avoid_tag_ids JSON DEFAULT NULL COMMENT '避免标签 ID 数组, 用于直接排除候选',
    MODIFY COLUMN max_budget DECIMAL(10, 2) DEFAULT NULL COMMENT '最高预算, V1 不做硬过滤',
    MODIFY COLUMN last_mode VARCHAR(20) DEFAULT 'LAZY' COMMENT '上次使用模式, 用于首页默认态恢复',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE shake_history COMMENT = '摇一摇历史表, 每次摇一摇都会落一条记录';
ALTER TABLE shake_history
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '主键 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID, 当前 V1 固定为 1',
    MODIFY COLUMN food_id BIGINT NOT NULL COMMENT '命中的食物 ID',
    MODIFY COLUMN food_name VARCHAR(100) NOT NULL COMMENT '冗余食物名称, 防止后续改名影响历史展示',
    MODIFY COLUMN mode VARCHAR(20) NOT NULL COMMENT '摇一摇模式, 如 LAZY, CLEAR, SPICY, LIGHT',
    MODIFY COLUMN trigger_type VARCHAR(20) NOT NULL COMMENT '触发方式, SHAKE 或 CLICK',
    MODIFY COLUMN result_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '结果状态, PENDING, ACCEPTED, REJECTED',
    MODIFY COLUMN ai_tip TEXT DEFAULT NULL COMMENT 'AI 或兜底文案',
    MODIFY COLUMN ai_source VARCHAR(20) NOT NULL DEFAULT 'FALLBACK' COMMENT '文案来源, OLLAMA 或 FALLBACK',
    MODIFY COLUMN prompt_snapshot TEXT DEFAULT NULL COMMENT '生成文案时的 prompt 快照, 便于排查',
    MODIFY COLUMN score_snapshot JSON DEFAULT NULL COMMENT '命中时的权重明细快照, 便于调权重',
    MODIFY COLUMN shake_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '摇出结果的时间',
    MODIFY COLUMN confirm_time DATETIME DEFAULT NULL COMMENT '用户点击就这样吃的确认时间';

